### ISSUE TITLE
Тестовая задача для CSC-AU-2017

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Examples#7]
Необходимо реализовать как минимум одно из следующих расширений калькулятора (проект [src/Calc](https://github.com/YaccConstructor/Examples/tree/master/src/Calc)). Реализация расширения подразумевает поддержку на уровне лексического и синтаксического анализов, в дереве разбора, в интерпретаторе выражений.
- Реализовать поддержку операции "модуль".
- Реализовать поддержку [стрелочной нотации Кнута](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B5%D0%BB%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%9A%D0%BD%D1%83%D1%82%D0%B0).
- Реализовать поддержку любых двух тригонометрических функций.

Задача решается в своём форке, сдаётся через pull request в master.
Технические вопросы можно задавать в комментариях к этому issue.

Немного подсказок для того, чтобы решения у всех получились разные.
- Модуль можно сделать с использованием классических "скобок": ``` | x - y | ```
- Для стрелок Кнута можно тоже разные значки поиспользовать. Например, ^: ```2^^^3 ```
- Тригонометрию можно лишить обязательных скобок. Пусть применение функций будет как в F# или Haskell. Оставить только группирующие скобки общего назначения.
- А ещё можно добавить тестов на реализованную функциональность :)

**Comment by HeyLey** [comment]
Вопрос: а вы уверены, что Program.fs из src/Calc отрабатывает нормально? Т.к. данная программа у меня программа прерывается с ошибкой, в отличие от BoolCalc.

**Comment by Albert1401** [comment]
в данной грамматике 2**3**2=64. Это считается правильным поведением?

**Comment by gsvgit** [comment]
@HeyLey На том примере, что там "зашит" изначально -- уверен. Если есть
проблемы, можете прислать сообщение об ошибке и/или добавить тест, её
воспроизводящий, чтобы я более детально изучил проблему.

Regards,
Semyon Grigorev.

17 февраля 2017 г., 14:57 пользователь Ley H. <notifications@github.com>
написал:

**Comment by gsvgit** [comment]
@Albert1401 если я правильно понял вопрос, то грамматика (без атрибутов)
задаёт только синтаксис. Синтаксически такое выражение корректно. Если
смущает семантика, то её всегда можно поправить. Всё в ваших руках)

Regards,
Semyon Grigorev.

2017-02-17 23:29 GMT+03:00 Albert1401 <notifications@github.com>:
